# Generated by Django 4.1.3 on 2022-11-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplied',
            old_name='comapany_name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='jobapplied',
            name='description',
        ),
    ]
